# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

n = int(input('Digite um número: '))
tab1 = int(n*1)
tab2 = int(n*2)
tab3 = int(n*3)
tab4 = int(n*4)
tab5 = int(n*4)
tab6 = int(n*6)
tab7 = int(n*7)
tab8 = int(n*8)
tab9 = int(n*9)
tab10 = int(n*10)
print('A tabuada de {} é:\n{}x1 = {} '.format(n, n, tab1))
print('{}x2 = {}'.format(n, tab2))
print('{}x3 = {}'.format(n, tab3))
print('{}x4 = {}'.format(n, tab4))
print('{}x5 = {}'.format(n, tab5))
print('{}x6 = {}'.format(n, tab6))
print('{}x7 = {}'.format(n, tab7))
print('{}x8 = {}'.format(n, tab8))
print('{}x9 = {}'.format(n, tab9))
print('{}x10 = {}'.format(n, tab10))

# Como o Guanabara fez:

# num = int(input('Digite um número para ver sua tabuada: '))
# print('-' * 12)
# print('{} x {:2} = {}'.format(num, 1, num*1))
# print('{} x {:2} = {}'.format(num, 2, num*2))
# print('{} x {:2} = {}'.format(num, 3, num*3))
# print('{} x {:2} = {}'.format(num, 4, num*4))
# print('{} x {:2} = {}'.format(num, 5, num*5))
# print('{} x {:2} = {}'.format(num, 6, num*6))
# print('{} x {:2} = {}'.format(num, 7, num*7))
# print('{} x {:2} = {}'.format(num, 8, num*8))
# print('{} x {:2} = {}'.format(num, 9, num*9))
# print('{} x {:2} = {}'.format(num, 10, num*10))
# print('-' * 12)
